services:
  mlflow:
    build:
      context: ./services/mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports: ["5000:5000"]
    volumes:
      - mlflow_db:/mlflow
      - mlartifacts:/mlruns
    networks: [mlnet]

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: prediction-api
    env_file: [.env]
    ports: ["8000:8000"]
    depends_on: [mlflow]
    networks: [mlnet]

networks:
  mlnet:
    driver: bridge

volumes:
  mlflow_db:
  mlartifacts:
