name: CI Pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
      - "feat/**"
      - "doc/**"
      - "chore/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_MODEL_LOAD: "1" # stub model in CI
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r services/api/requirements.txt
          pip install pytest dvc httpx
      - name: DVC sanity
        run: |
          dvc --version
          dvc status -c || true
          dvc repro --dry || true
          dvc dag || true
      - name: Run tests
        run: pytest -q

  build-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build API Docker image
        run: |
          docker build -f services/api/Dockerfile -t penguins-api:${{ github.sha }} .
